/* STEMMate Namibia prototype - SYNTHETIC DATA ONLY.
   Every activity, facilitator profile and count below is fictional and was
   created for demonstration and classroom testing. No real person, school or
   learner is described. */
window.STEM_DATA = {
  version: "v1.0.0 (A3 prototype, 2026-09-29)",
  storageLimitKB: 6000, // simulated device quota for offline content
  profiles: [
    { id: "fac-a", label: "Facilitator A (synthetic profile)", role: "Facilitator", pin: "1234" },
    { id: "vol-b", label: "Volunteer B (synthetic profile)", role: "Volunteer assistant", pin: "2468" }
  ],
  levels: ["Upper primary (Gr 4-7)", "Junior secondary (Gr 8-9)", "Senior secondary (Gr 10-12)"],
  topics: ["Physics", "Chemistry", "Biology", "Mathematics", "Engineering", "Earth science"],
  materials: ["Plastic bottles", "Cardboard", "String", "Bottle caps", "Sand", "Water", "Straws", "Tape", "Rubber bands", "Salt", "Vinegar", "Baking soda", "Seeds", "Ruler"],
  activities: [
    { id: "ACT-01", title: "Bottle hydraulic lift", level: "Junior secondary (Gr 8-9)", topic: "Physics", minutes: 45,
      materials: ["Plastic bottles", "Straws", "Water", "Tape"], sizeKB: 1350,
      summary: "Learners connect two bottles with a straw to see how pressure moves a load.",
      imageAlt: "Line drawing of two plastic bottles joined by a straw, one lifting a small cardboard platform.",
      steps: ["Fill one bottle two-thirds with water.", "Join both bottle caps with a straw and seal with tape.", "Squeeze bottle 1 and observe the platform on bottle 2.", "Discuss where the force went."],
      safety: "Wipe spills at once to prevent slipping.", inclusion: "Pair learners so one squeezes and one records; swap roles." },
    { id: "ACT-02", title: "Solar still for clean water", level: "Senior secondary (Gr 10-12)", topic: "Earth science", minutes: 60,
      materials: ["Plastic bottles", "Water", "Salt", "Tape"], sizeKB: 1800,
      summary: "Build a small solar still and measure how much fresh water condenses.",
      imageAlt: "Diagram of a cut bottle over a cup of salty water, with arrows showing evaporation and condensation.",
      steps: ["Mix salty water in the base.", "Place the cut bottle top over the base.", "Leave in direct sun for 30 minutes.", "Measure the condensed water with a marked cup and compare groups."],
      safety: "Cover cut plastic edges with tape. Do not drink the water.", inclusion: "Offer a printed step card for learners who prefer reading to listening." },
    { id: "ACT-03", title: "Seed germination race", level: "Upper primary (Gr 4-7)", topic: "Biology", minutes: 30,
      materials: ["Seeds", "Water", "Cardboard", "Ruler"], sizeKB: 900,
      summary: "Compare seed growth in different conditions over one week.",
      imageAlt: "Three small cups with seedlings of different heights next to a ruler.",
      steps: ["Label three cups: light, dark, no water.", "Plant two seeds in each.", "Measure daily with the ruler.", "Plot the results on the board."],
      safety: "Wash hands after handling soil.", inclusion: "Use large, high-contrast labels on the cups." },
    { id: "ACT-04", title: "Fizzing volcano reaction", level: "Upper primary (Gr 4-7)", topic: "Chemistry", minutes: 20,
      materials: ["Vinegar", "Baking soda", "Plastic bottles", "Sand"], sizeKB: 700,
      summary: "Observe an acid-base reaction and name the gas produced.",
      imageAlt: "A sand mound around a small bottle with foam overflowing from the top.",
      steps: ["Build a sand mound around the bottle.", "Add two spoons of baking soda.", "Pour in vinegar slowly.", "Ask: what gas made the bubbles?"],
      safety: "Keep vinegar away from eyes; stand back while pouring.", inclusion: "Describe each change aloud for learners with low vision." },
    { id: "ACT-05", title: "Cardboard bridge challenge", level: "Junior secondary (Gr 8-9)", topic: "Engineering", minutes: 60,
      materials: ["Cardboard", "Tape", "String", "Bottle caps"], sizeKB: 1600,
      summary: "Teams design a bridge that spans 30 cm and holds the most bottle caps.",
      imageAlt: "A folded cardboard bridge between two books, holding a pile of bottle caps.",
      steps: ["Set the 30 cm gap.", "Give each team one sheet of cardboard and tape.", "Build for 25 minutes.", "Load bottle caps one at a time and record the count."],
      safety: "Scissors are handled by the facilitator only.", inclusion: "Assign roles: builder, tester, recorder, presenter." },
    { id: "ACT-06", title: "Bottle-cap fractions", level: "Upper primary (Gr 4-7)", topic: "Mathematics", minutes: 30,
      materials: ["Bottle caps", "Cardboard"], sizeKB: 450,
      summary: "Use coloured bottle caps on a cardboard grid to model fractions.",
      imageAlt: "A cardboard grid of eight squares with three squares covered by bottle caps.",
      steps: ["Draw an 8-square grid.", "Cover 3 squares and write 3/8.", "Learners create and swap their own fractions."],
      safety: "Check caps have no sharp edges.", inclusion: "Allow learners to say, write or show the fraction." },
    { id: "ACT-07", title: "Straw rocket launch", level: "Junior secondary (Gr 8-9)", topic: "Physics", minutes: 45,
      materials: ["Straws", "Cardboard", "Tape", "Ruler"], sizeKB: 1100,
      summary: "Investigate how fin shape changes the distance a paper rocket travels.",
      imageAlt: "A paper rocket on a straw launcher with a tape measure on the floor.",
      steps: ["Roll a paper tube around a straw.", "Add cardboard fins.", "Blow through the straw to launch.", "Measure distance for three fin designs."],
      safety: "Launch away from faces; one straw per learner.", inclusion: "Provide a hand pump alternative for learners with limited breath control." },
    { id: "ACT-08", title: "Salt crystal growing", level: "Senior secondary (Gr 10-12)", topic: "Chemistry", minutes: 45,
      materials: ["Salt", "Water", "String"], sizeKB: 800,
      summary: "Grow salt crystals and relate crystal size to cooling rate.",
      imageAlt: "A string hanging in a jar of salty water with small crystals forming on it.",
      steps: ["Dissolve salt in warm water until saturated.", "Hang a string in the jar.", "Leave one jar warm and one cool.", "Compare crystals after two days."],
      safety: "Use warm, not boiling, water.", inclusion: "Offer a magnifier and let learners describe crystals verbally or by sketch." },
    { id: "ACT-09", title: "Rubber-band force meter", level: "Junior secondary (Gr 8-9)", topic: "Physics", minutes: 30,
      materials: ["Rubber bands", "Cardboard", "Ruler", "Bottle caps"], sizeKB: 600,
      summary: "Calibrate a simple force meter using bottle caps as standard weights.",
      imageAlt: "A rubber band hanging from a cardboard scale with a cup of bottle caps attached.",
      steps: ["Mark a zero line on the cardboard.", "Add caps five at a time.", "Mark the stretch each time.", "Use the meter to estimate an unknown load."],
      safety: "Do not overstretch bands near eyes.", inclusion: "Use a tactile scale with notches for learners with low vision." },
    { id: "ACT-10", title: "Sand erosion model", level: "Upper primary (Gr 4-7)", topic: "Earth science", minutes: 30,
      materials: ["Sand", "Water", "Cardboard"], sizeKB: 750,
      summary: "Model how running water shapes the land using a sand tray.",
      imageAlt: "A tilted cardboard tray of sand with a small channel cut by trickling water.",
      steps: ["Tilt a sand-filled tray.", "Pour water slowly at the top.", "Observe the channel.", "Add stones and repeat."],
      safety: "Do the activity outdoors or on a covered floor.", inclusion: "Allow learners to feel the channel shape with their fingers." }
  ],
  /* Simulated server copy used to demonstrate a version conflict. */
  serverEditNote: "Coordinator (synthetic) shortened step 3 and added a safety note on the server copy."
};
